name: fb_auth
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
 
  cloud_firestore: any
  equatable: ^2.0.5
  firebase_core: any
  collection: any
  firebase_auth: ^4.6.2

  
 
  flutter:
    sdk: flutter
  provider: ^6.0.5
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  assets/
